service: mern-backend-api

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-south-1'}
  environment:
    NODE_ENV: ${env:NODE_ENV, 'dev'}
    MONGO_URI: ${env:MONGO_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    CLIENT_URL: ${env:CLIENT_URL}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline

package:
  patterns:
    - "!node_modules/.bin/**"
    - "!src/**"
    - "!.git/**"
    - "!.github/**"
    - "!.gitignore"
    - "!.serverless/**"
    - "!test/**"
    - "!tsconfig.json"
    - "dist/**"