name: Deploy MERN App to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ========== FRONTEND (React) ==========
    - name: Install frontend dependencies
      working-directory: ./client
      run: npm install

    - name: Build frontend
      working-directory: ./client
      run: npm run build

    - name: Deploy to S3
      run: |
        aws s3 sync ./client/dist s3://$S3_BUCKET_NAME --delete --region $AWS_REGION

    - name: Invalidate CloudFront Cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
          --paths "/*"

    # ========== BACKEND (Express → Lambda) ==========
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Serverless CLI
      run: npm install -g serverless

    - name: Install backend dependencies
      working-directory: ./server
      run: npm install

    - name: Deploy backend to Lambda
      working-directory: ./server
      run: sls deploy --stage prod --region $AWS_REGION
